"""Project publish/install: serialize a Project's authored config to a shareable bundle.

A bundle is a directory (destined for a `pam-{project}` git repo) holding a text manifest
(`pam.project.toml`) plus authored asset dirs (roles/skills/oracle/actions/recipes). It contains
only the AUTHORED, shareable half: project identity, repos (url + default-branch, never local
paths), and project-scoped roles. It NEVER contains recorded state (agents, memberships, sessions,
claimed issues, epics, phase), which is local to each machine and regenerated on install. No
`.db` is ever written to a bundle.

`publish()` writes the bundle; `install()` reads it, binds the installer's local values (checkout
paths, gh account), and generates fresh local registry rows. The installer staffs their own agents.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

from . import db, gitutil

try:  # py3.11+
    import tomllib
except ModuleNotFoundError:  # pragma: no cover
    tomllib = None

MANIFEST = "pam.project.toml"
ASSET_DIRS = ("roles", "skills", "oracle", "actions", "recipes")


# ---- minimal TOML emitter (stdlib has a reader but no writer) ----------------

def _toml_scalar(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, list):
        return "[" + ", ".join(_toml_scalar(x) for x in v) + "]"
    s = str(v).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{s}"'


def _emit_table(name, d, lines, array=False):
    lines.append(f"[[{name}]]" if array else f"[{name}]")
    for k, v in d.items():
        if v is not None:
            lines.append(f"{k} = {_toml_scalar(v)}")
    lines.append("")


def dump_toml(manifest: dict) -> str:
    lines: list[str] = [
        "# PAM Project bundle manifest: authored, shareable config only.",
        "# Generated by `pam project publish`. No recorded state here; edit freely and commit.",
        "",
    ]
    _emit_table("project", manifest["project"], lines)
    if manifest.get("bindings"):
        _emit_table("bindings", manifest["bindings"], lines)
    for r in manifest.get("repos", []):
        _emit_table("repos", r, lines, array=True)
    for role in manifest.get("roles", []):
        _emit_table("roles", role, lines, array=True)
    return "\n".join(lines)


def _load_manifest(path: Path) -> dict:
    if tomllib is None:
        raise RuntimeError("tomllib unavailable (needs Python 3.11+)")
    with path.open("rb") as fh:
        return tomllib.load(fh)


# ---- publish ----------------------------------------------------------------

def build_manifest(project_ref) -> dict:
    prog = db.get_project(project_ref)
    if not prog:
        raise ValueError(f"no such project: {project_ref}")
    repos = db.list_repos(prog["id"])
    # project-scoped roles only (built-ins ship with PAM; don't re-publish them)
    roles = [r for r in db.list_roles(prog["id"]) if r["project_id"] == prog["id"]]
    return {
        "project": {
            "name": prog["name"],
            "framework": prog["framework"],
            "tracker": prog["tracker"],
        },
        "bindings": {
            # declared, filled at install time; never the values themselves
            "gh_account": True,
            "repo_paths": [r["name"] for r in repos],
        },
        "repos": [
            {"name": r["name"], "repo_url": r["repo_url"],
             "default_branch": r["default_branch"]}
            for r in repos
        ],
        "roles": [
            {"key": r["key"], "title": r["title"], "description": r["description"],
             "permissions": json.loads(r["permissions"] or "[]"),
             "config": r["config"] or "{}"}
            for r in roles
        ],
    }


def publish(project_ref, out_dir: Optional[str] = None) -> Path:
    prog = db.get_project(project_ref)
    if not prog:
        raise ValueError(f"no such project: {project_ref}")
    manifest = build_manifest(project_ref)
    out = Path(out_dir) if out_dir else Path.cwd() / f"pam-{prog['name'].lower()}"
    out.mkdir(parents=True, exist_ok=True)
    (out / MANIFEST).write_text(dump_toml(manifest))
    # scaffold the authored asset dirs so contributors know where things go
    for d in ASSET_DIRS:
        (out / d).mkdir(exist_ok=True)
        keep = out / d / ".gitkeep"
        if not any(p for p in (out / d).iterdir()):
            keep.write_text("")
    return out


# ---- install ----------------------------------------------------------------

def install(bundle_dir, name: Optional[str] = None,
            repo_paths: Optional[dict] = None, gh_account: Optional[str] = None,
            force: bool = False) -> dict:
    bundle = Path(bundle_dir)
    manifest_path = bundle / MANIFEST
    if not manifest_path.exists():
        raise ValueError(f"no {MANIFEST} in {bundle}")
    manifest = _load_manifest(manifest_path)
    pname = name or manifest["project"]["name"]
    if db.get_project(pname):
        raise ValueError(f"a Project named '{pname}' already exists locally "
                         f"(install with --name to rename)")
    repo_paths = repo_paths or {}
    required = [r["name"] for r in manifest.get("repos", [])]
    missing = [n for n in required if n not in repo_paths]
    if missing and not force:
        raise ValueError("missing --repo-path for: " + ", ".join(missing)
                         + " (local checkout paths must be bound at install)")

    prog = db.add_project(
        name=pname,
        framework=manifest["project"].get("framework"),
        tracker=manifest["project"].get("tracker", "github"),
        gh_account=gh_account,
    )
    for r in manifest.get("repos", []):
        path = repo_paths.get(r["name"])
        if not path:
            continue
        origin = gitutil.origin(path)
        if origin and not gitutil.same_repo(origin, r["repo_url"]) and not force:
            raise ValueError(
                f"origin mismatch for repo '{r['name']}': {origin} != {r['repo_url']}")
        db.add_repo(prog["id"], name=r["name"], repo_url=r["repo_url"], path=path,
                    origin=origin or r["repo_url"],
                    default_branch=r.get("default_branch", "main"))
    for role in manifest.get("roles", []):
        db.add_role(prog["id"], role["key"], role.get("title"), role.get("description"),
                    role.get("permissions", []), role.get("config", "{}"))
    return prog
